"""Add Phase 1.2 error handling - retry fields and StoryFailure DLQ

Revision ID: 5ef8b44af819
Revises: 
Create Date: 2025-10-09 16:29:41.299855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5ef8b44af819'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Get existing enum type (it should already exist from current_step column)
    workflow_step_enum = postgresql.ENUM('QUEUED', 'STORY_GENERATION', 'TITLE_GENERATION', 
                                          'IMAGE_GENERATION', 'AUDIO_GENERATION', 'VIDEO_GENERATION', 
                                          'YOUTUBE_UPLOAD', 'GHOST_PUBLISHING', 'COMPLETED', 'FAILED', 
                                          name='workflowstep', create_type=False)
    
    # Add retry fields to stories table with server defaults for existing rows
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('max_retries', sa.Integer(), nullable=False, server_default='5'))
        batch_op.add_column(sa.Column('last_retry_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_retry_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('error_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('failed_at_step', workflow_step_enum, nullable=True))

    # Create story_failures table for Dead Letter Queue
    op.create_table('story_failures',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('story_id', sa.Integer(), nullable=False),
        sa.Column('failed_at_step', workflow_step_enum, nullable=False),
        sa.Column('error_type', sa.String(length=50), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=False),
        sa.Column('stack_trace', sa.Text(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('failure_reason', sa.Text(), nullable=True),
        sa.Column('can_retry', sa.Boolean(), nullable=False),
        sa.Column('requires_intervention', sa.Boolean(), nullable=False),
        sa.Column('dlq_status', sa.String(length=20), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.Column('resolved_by', sa.Integer(), nullable=True),
        sa.Column('resolution_notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('story_id')
    )
    with op.batch_alter_table('story_failures', schema=None) as batch_op:
        batch_op.create_index('idx_story_failure_error_type', ['error_type'], unique=False)
        batch_op.create_index('idx_story_failure_priority', ['priority', 'created_at'], unique=False)
        batch_op.create_index('idx_story_failure_status', ['dlq_status'], unique=False)
        batch_op.create_index('idx_story_failure_step', ['failed_at_step'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop story_failures table
    with op.batch_alter_table('story_failures', schema=None) as batch_op:
        batch_op.drop_index('idx_story_failure_step')
        batch_op.drop_index('idx_story_failure_status')
        batch_op.drop_index('idx_story_failure_priority')
        batch_op.drop_index('idx_story_failure_error_type')

    op.drop_table('story_failures')
    
    # Drop retry fields from stories table
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('failed_at_step')
        batch_op.drop_column('error_type')
        batch_op.drop_column('next_retry_at')
        batch_op.drop_column('last_retry_at')
        batch_op.drop_column('max_retries')
        batch_op.drop_column('retry_count')

    # ### end Alembic commands ###
